import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Header from "@/components/Header";
=======
>>>>>>> 77a0381 (Initial commit from Create Next App)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Movies App",
=======
  title: "Create Next App",
>>>>>>> 77a0381 (Initial commit from Create Next App)
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 77a0381 (Initial commit from Create Next App)
    </html>
  );
}
